[project]
name = "banana-netcraze"
dynamic = ["version"]
description = "UNOFFICIAL python library for Keenetic/Netcraze routers"
requires-python = ">=3.13,<3.14"
dependencies = [
    "httpx>=0.28.1",
    "loguru>=0.0.0",
    "pydantic>=2.13.4",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/BananaLoaf/banana-netcraze"
Documentation = "https://github.com/BananaLoaf/banana-netcraze"
Repository = "https://github.com/BananaLoaf/banana-netcraze.git"
Issues = "https://github.com/BananaLoaf/banana-netcraze/issues"
Changelog = "https://github.com/BananaLoaf/banana-netcraze/releases"

[project.optional-dependencies]
cli = [
    "typer>=0.27.0",
]

[dependency-groups]
dev = [
    "mypy>=2.1.0",
    "poethepoet>=0.46.0",
    "pytest>=9.0.3",
    "ruff>=0.15.16",
]




[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.hatch.build]
include = ["banana_netcraze"]




[tool.uv-dynamic-versioning]
style = "semver"
vcs = "git"
fallback-version = "0.0.0"




[tool.pytest.ini_options]
testpaths = ["tests"]




[project.scripts]
banana-netcraze = "banana_netcraze.__main__:app"

[project.gui-scripts]

[tool.poe.tasks]
lint-format = "ruff format ."
lint-check = "ruff check --fix --extend-select I ."
lint = ["lint-format", "lint-check"]
test = "pytest"
typecheck = "mypy banana_netcraze/"
